package at.mchristoph.lapse.dao.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import at.mchristoph.lapse.dao.model.LapseSetting;
import at.mchristoph.lapse.dao.model.LapseHistory;

import at.mchristoph.lapse.dao.model.LapseSettingDao;
import at.mchristoph.lapse.dao.model.LapseHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lapseSettingDaoConfig;
    private final DaoConfig lapseHistoryDaoConfig;

    private final LapseSettingDao lapseSettingDao;
    private final LapseHistoryDao lapseHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lapseSettingDaoConfig = daoConfigMap.get(LapseSettingDao.class).clone();
        lapseSettingDaoConfig.initIdentityScope(type);

        lapseHistoryDaoConfig = daoConfigMap.get(LapseHistoryDao.class).clone();
        lapseHistoryDaoConfig.initIdentityScope(type);

        lapseSettingDao = new LapseSettingDao(lapseSettingDaoConfig, this);
        lapseHistoryDao = new LapseHistoryDao(lapseHistoryDaoConfig, this);

        registerDao(LapseSetting.class, lapseSettingDao);
        registerDao(LapseHistory.class, lapseHistoryDao);
    }
    
    public void clear() {
        lapseSettingDaoConfig.getIdentityScope().clear();
        lapseHistoryDaoConfig.getIdentityScope().clear();
    }

    public LapseSettingDao getLapseSettingDao() {
        return lapseSettingDao;
    }

    public LapseHistoryDao getLapseHistoryDao() {
        return lapseHistoryDao;
    }

}
