package at.mchristoph.lapse.dao.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import at.mchristoph.lapse.dao.model.LapseSetting;

import at.mchristoph.lapse.dao.model.LapseSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lapseSettingDaoConfig;

    private final LapseSettingDao lapseSettingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lapseSettingDaoConfig = daoConfigMap.get(LapseSettingDao.class).clone();
        lapseSettingDaoConfig.initIdentityScope(type);

        lapseSettingDao = new LapseSettingDao(lapseSettingDaoConfig, this);

        registerDao(LapseSetting.class, lapseSettingDao);
    }
    
    public void clear() {
        lapseSettingDaoConfig.getIdentityScope().clear();
    }

    public LapseSettingDao getLapseSettingDao() {
        return lapseSettingDao;
    }

}
