package at.mchristoph.lapse.dao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LAPSE_SETTING".
 */
public class LapseSetting {

    private Long id;
    /** Not-null value. */
    private String name;
    private String description;
    private long framerate;
    private long interval;
    private long movie_time;
    /** Not-null value. */
    private java.util.Date created;

    public LapseSetting() {
    }

    public LapseSetting(Long id) {
        this.id = id;
    }

    public LapseSetting(Long id, String name, String description, long framerate, long interval, long movie_time, java.util.Date created) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.framerate = framerate;
        this.interval = interval;
        this.movie_time = movie_time;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getFramerate() {
        return framerate;
    }

    public void setFramerate(long framerate) {
        this.framerate = framerate;
    }

    public long getInterval() {
        return interval;
    }

    public void setInterval(long interval) {
        this.interval = interval;
    }

    public long getMovie_time() {
        return movie_time;
    }

    public void setMovie_time(long movie_time) {
        this.movie_time = movie_time;
    }

    /** Not-null value. */
    public java.util.Date getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(java.util.Date created) {
        this.created = created;
    }

}
