package at.mchristoph.lapse.dao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LAPSE_HISTORY".
 */
public class LapseHistory {

    private Long id;
    private long framerate;
    private long interval;
    private long movieTime;
    private String location;
    /** Not-null value. */
    private java.util.Date created;

    public LapseHistory() {
    }

    public LapseHistory(Long id) {
        this.id = id;
    }

    public LapseHistory(Long id, long framerate, long interval, long movieTime, String location, java.util.Date created) {
        this.id = id;
        this.framerate = framerate;
        this.interval = interval;
        this.movieTime = movieTime;
        this.location = location;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getFramerate() {
        return framerate;
    }

    public void setFramerate(long framerate) {
        this.framerate = framerate;
    }

    public long getInterval() {
        return interval;
    }

    public void setInterval(long interval) {
        this.interval = interval;
    }

    public long getMovieTime() {
        return movieTime;
    }

    public void setMovieTime(long movieTime) {
        this.movieTime = movieTime;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    /** Not-null value. */
    public java.util.Date getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(java.util.Date created) {
        this.created = created;
    }

}
